// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtNWetd8Spkg_sE-2YA_6l8aSdUaB8yDY',
    appId: '1:534427283717:web:d6d6a85b82e03352d1c76c',
    messagingSenderId: '534427283717',
    projectId: 'jarvis-tech-stack',
    authDomain: 'jarvis-tech-stack.firebaseapp.com',
    databaseURL: 'https://jarvis-tech-stack-default-rtdb.firebaseio.com',
    storageBucket: 'jarvis-tech-stack.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcc52wuDZ6geIXWuAFN5Xk2uDnvnJPCDM',
    appId: '1:534427283717:android:f11d502ae7969ca9d1c76c',
    messagingSenderId: '534427283717',
    projectId: 'jarvis-tech-stack',
    databaseURL: 'https://jarvis-tech-stack-default-rtdb.firebaseio.com',
    storageBucket: 'jarvis-tech-stack.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRkIu4KEkS4sAodtAeHy7HJtLNuXYaLwo',
    appId: '1:534427283717:ios:c10b012ad0af3c00d1c76c',
    messagingSenderId: '534427283717',
    projectId: 'jarvis-tech-stack',
    databaseURL: 'https://jarvis-tech-stack-default-rtdb.firebaseio.com',
    storageBucket: 'jarvis-tech-stack.appspot.com',
    iosBundleId: 'com.example.jarvisTechStack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRkIu4KEkS4sAodtAeHy7HJtLNuXYaLwo',
    appId: '1:534427283717:ios:241286c2e7647a0ad1c76c',
    messagingSenderId: '534427283717',
    projectId: 'jarvis-tech-stack',
    databaseURL: 'https://jarvis-tech-stack-default-rtdb.firebaseio.com',
    storageBucket: 'jarvis-tech-stack.appspot.com',
    iosBundleId: 'com.example.jarvisTechStack.RunnerTests',
  );
}
